name: Building Kernel gcc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare the environment
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y flex bc bison git python zip build-essential tar wget swig python3-dev
          sudo apt clean

      - name: Install toolchain
        run: |
          mkdir -p workspace
          cd workspace
          wget -q https://snapshots.linaro.org/gnu-toolchain/13.0-2022.11-1/aarch64-linux-gnu/gcc-linaro-13.0.0-2022.11-x86_64_aarch64-linux-gnu.tar.xz
          wget -q https://snapshots.linaro.org/gnu-toolchain/13.0-2022.11-1/arm-linux-gnueabihf/gcc-linaro-13.0.0-2022.11-x86_64_arm-linux-gnueabihf.tar.xz
          tar -xf gcc-linaro-13.0.0-2022.11-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf gcc-linaro-13.0.0-2022.11-x86_64_arm-linux-gnueabihf.tar.xz
          rm -rf gcc-linaro-13.0.0-2022.11-x86_64_aarch64-linux-gnu.tar.xz
          rm -rf gcc-linaro-13.0.0-2022.11-x86_64_arm-linux-gnueabihf.tar.xz
          mv gcc-linaro-13.0.0-2022.11-x86_64_aarch64-linux-gnu gcc-arm64
          mv gcc-linaro-13.0.0-2022.11-x86_64_arm-linux-gnueabihf gcc-arm

      - name: Clone repo
        run: |
          cd workspace
          sudo hostname jzinferno
          git config --global user.name "jzinferno"
          git config --global user.email "jekazinferno@gmail.com"
          git clone --depth=1 https://github.com/jzinferno/anykernel.git anykernel
          git clone --depth=1 https://github.com/jzinferno/kernel_lenovo_sdm710.git kernel
          git clone --depth=1 https://github.com/lz4/lz4.git
          git clone --depth=1 https://git.kernel.org/pub/scm/utils/dtc/dtc.git

      - name: Make deps
        run: |
          cd workspace/lz4
          make -j$(nproc --all)
          ln -s lz4 lz4c
          cd ../dtc
          make NO_PYTHON=1 -j$(nproc --all)

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Build gcc jd2019
        run: |
          export PATH=$(realpath workspace/gcc-arm64/bin):$PATH
          export PATH=$(realpath workspace/gcc-arm/bin):$PATH
          export PATH=$(realpath workspace/lz4):$PATH
          export DTC=$(realpath workspace/dtc/dtc)
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabihf-
          export CROSS_COMPILE=aarch64-linux-gnu-
          cd workspace/kernel
          rm -rf out
          sed -i 's/CONFIG_TOOLS_SUPPORT_RELR=y//g' arch/arm64/configs/jd2019_defconfig
          make DTC=$DTC O=out ARCH=arm64 jd2019_defconfig
          make DTC=$DTC O=out ARCH=arm64 -j$(nproc --all)
          cd ../anykernel/jd2019
          mv ../../kernel/out/arch/arm64/boot/Image.lz4-dtb .
          mv ../../kernel/out/arch/arm64/boot/dtbo.img .
          cp -r ../bin .
          zip -r9 jd2019_kernel_gcc_$(date +%Y%m%d).zip META-INF bin Image.lz4-dtb dtbo.img

      - name: Build gcc kunlun2
        run: |
          export PATH=$(realpath workspace/gcc-arm64/bin):$PATH
          export PATH=$(realpath workspace/gcc-arm/bin):$PATH
          export PATH=$(realpath workspace/lz4):$PATH
          export DTC=$(realpath workspace/dtc/dtc)
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabihf-
          export CROSS_COMPILE=aarch64-linux-gnu-
          cd workspace/kernel
          rm -rf out
          sed -i 's/CONFIG_TOOLS_SUPPORT_RELR=y//g' arch/arm64/configs/kunlun2_defconfig
          make DTC=$DTC O=out ARCH=arm64 kunlun2_defconfig
          make DTC=$DTC O=out ARCH=arm64 -j$(nproc --all)
          cd ../anykernel/kunlun2
          mv ../../kernel/out/arch/arm64/boot/Image.lz4-dtb .
          mv ../../kernel/out/arch/arm64/boot/dtbo.img .
          cp -r ../bin .
          zip -r9 kunlun2_kernel_gcc_$(date +%Y%m%d).zip META-INF bin Image.lz4-dtb dtbo.img

      - name: Release kernel
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: kernel_${{ github.run_id }}
          files: |
            workspace/anykernel/*/*.zip
