name: Testing commands

on:
  workflow_dispatch:
    inputs:
      COMMANDS:
        description: 'COMMANDS'
        required: true
        default: 'neofetch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Testing
        run: |
          ${{ github.event.inputs.COMMANDS }}
