name: Building Kernel sdm710

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare the environment
        run: |
          sudo apt update -y
          sudo apt install -y flex bc bison git python2 zip build-essential tar wget swig python3-dev lz4
          sudo apt clean

      - name: Install toolchain
        run: |
          mkdir -p workspace
          cd workspace
          mkdir -p clang anykernel && cd clang
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r487747.tar.gz
          tar -xf clang-*.tar.gz
          rm -rf *.tar.gz

      - name: Clone repo
        run: |
          cd workspace
          sudo hostname jzinferno
          git config --global user.name "jzinferno2"
          git config --global user.email "jekazinferno@gmail.com"
          git clone --depth=1 https://github.com/jzinferno2/kernel_lenovo_sdm710.git kernel

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Build clang jd2019
        run: |
          export PATH=$(realpath workspace/clang/bin):$PATH
          cd workspace/kernel
          rm -rf out
          make LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 jd2019_defconfig
          make LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 -j$(nproc --all)
          cd out/arch/arm64/boot
          zip -r9 jd2019_kernel_$(date +%Y%m%d).zip META-INF bin files Image.lz4-dtb
          mv *.zip ../../../../../anykernel

      - name: Build clang kunlun2
        run: |
          export PATH=$(realpath workspace/clang/bin):$PATH
          cd workspace/kernel
          rm -rf out
          make LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 kunlun2_defconfig
          make LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 -j$(nproc --all)
          cd out/arch/arm64/boot
          zip -r9 kunlun2_kernel_$(date +%Y%m%d).zip META-INF bin files Image.lz4-dtb
          mv *.zip ../../../../../anykernel

      - name: Release kernel
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: kernel_${{ github.run_id }}
          files: |
            workspace/anykernel/*
