name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build APKs
        shell: bash {0}
        run: |
          exit_on_error() { echo "$1"; exit 1; }

          yes
