name: Building zippo OrangeFox recovery

on:
  workflow_dispatch:

env:
  DEVICE_TREE_URL: https://github.com/chematelegram/android_device_lenovo_zippo-twrp.git
  DEVICE_PATH: device/lenovo/zippo
  DEVICE_NAME: zippo
  DEVICE_VARIANT: twrp
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python aria2 libncurses5 python3
          sudo apt clean

      - name: Install repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Initialize repo
        run: |
          mkdir workspace
          git config --global user.name 'jzinferno'
          git config --global user.email 'jekazinferno@gmail.com'
          git clone --depth=1 https://gitlab.com/OrangeFox/sync.git
          cd sync
          ./orangefox_sync.sh --branch 11.0 --path ../workspace
          cd .. && rm -rf sync

      - name: Clone device tree
        run: |
          git clone --depth=1 $DEVICE_TREE_URL ./workspace/$DEVICE_PATH

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Building recovery
        run: |
          sudo fallocate -l 4G $HOME/swapjz
          sudo chmod 600 $HOME/swapjz
          sudo mkswap $HOME/swapjz
          sudo swapon $HOME/swapjz
          cd workspace
          export PATH=/opt/hostedtoolcache/Java_Adopt_jdk/11.0.16-101/x64/bin:$PATH
          if [ -f build/envsetup.sh ]; then
            source build/envsetup.sh
          fi
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          lunch "$DEVICE_VARIANT"_"$DEVICE_NAME"-eng && mka recoveryimage

      - name: Release recovery
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          body: |
            Text: 'build OrangeFox 12.1 zippo'
          name: TeamWin
          files: |
            workspace/out/target/product/*/OrangeFox*.zip
            workspace/out/target/product/*/recovery.img
